export const FACILITIES_REQUESTED = 'orgunits.FACILITIES_REQUESTED'
export const FACILITIES_RECEIVED = 'orgunits.FACILITIES_RECEIVED'
export const ADD_FACILITIES = 'orgunits.ADD_FACILITIES'

export const ORGUNIT_REQUESTED = 'orgunits.ORGUNIT_REQUESTED'
export const ORGUNIT_RECEIVED = 'orgunits.ORGUNIT_RECEIVED'
export const ADD_ORGUNITS = 'orgunits.ADD_ORGUNITS'