export const FACILITIES_REQUESTED = 'orgunits.FACILITIES_REQUESTED'
export const FACILITIES_RECEIVED = 'orgunits.FACILITIES_RECEIVED'

export const MFL_FACILITIES_REQUESTED = 'mfl.orgunits.FACILITIES_REQUESTED'
export const MFL_FACILITIES_RECEIVED = 'mfl.orgunits.FACILITIES_RECEIVED'

export const MFL_FACILITY_RESOLUTION_STARTED = 'mfl.orgunits.FACILITY_RESOLUTION_STARTED'
export const MFL_FACILITY_RESOLUTION_COMPLETED = 'mfl.orgunits.FACILITY_RESOLUTION_COMPLETED'